name: build multiplatform images

on:
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'test'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          #-
          #  name: Login to Docker Hub
          #  uses: docker/login-action@v1
          #  with:
          #    username: ${{ secrets.DOCKERHUB_USERNAME }}
          #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64,amd64
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - id: get_version
        name: Get Image Tag Name
        run: |
          if [ x${{ github.event.inputs.tag }} == x"" ]; then
            echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          else
            echo ::set-output name=VERSION::"${{github.event.inputs.tag}}"
          fi
      - 
        name: Build docker images
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ghcr.io/jmcarbo/redirecthttps:${{ steps.get_version.outputs.VERSION }} --file docker/Dockerfile .
